[supervisord]
nodaemon=true
user=root
logfile=/dev/stderr
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F -c /usr/local/etc/php-fpm.conf
priority=999
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/proc/self/fd/1
stderr_logfile=/proc/self/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
startretries=5
startsecs=10

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
priority=1000
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/proc/self/fd/1
stderr_logfile=/proc/self/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
startretries=5
startsecs=5
